/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * MailSetupPanel.java
 *
 * Created on Mar 3, 2011, 2:13:42 AM
 */

/**
 *
 * @author SWORD
 */
public class MailSetupPanel extends javax.swing.JFrame
{

    /** Creates new form MailSetupPanel */
    String user_name,password;
    MailViewPanel mp;
    javax.swing.JFrame frame = new javax.swing.JFrame("Simple Mail Validation tool");
    myThread m1=new myThread();
    public MailSetupPanel() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_user_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        b_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel1.setText("E-mail Address");
        jPanel1.add(jLabel1);
        jPanel1.add(tf_user_name);

        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jPanel1.add(pf_password);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Server Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel3.setText("Account Type");
        jPanel2.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POP3", "IMAP" }));
        jPanel2.add(jComboBox1);

        jLabel4.setText("Incoming Mail Server");
        jPanel2.add(jLabel4);
        jPanel2.add(jPasswordField2);

        b_ok.setText("ok");
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_ok)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(b_ok)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        // TODO add your handling code here:
        user_name=tf_user_name.getText();
        password=pf_password.getText();
        System.out.println(user_name+" "+password);
        mp=new MailViewPanel();  
        setVisible(false);
        System.out.println("chk1");
        
         
       class readMailThread extends Thread
        {
               
           public readMailThread()
            {
                
           }

            @Override
           public void run()
            {
                try {
                    mp.readMail("abu.saif01@gmail.com", "01714388766");
                } catch (IOException ex) {
                    Logger.getLogger(MailSetupPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
        System.out.println("chk2");

        frame.setLayout(new BorderLayout());
        frame.setSize(1000,800);
        frame.add(mp);
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

           }
        }
       
       readMailThread rmsth=new readMailThread();
        m1.start();
        
        rmsth.start();
        System.out.println("alive");


        class managewindow extends Thread
        {

           public managewindow()
            {

           }

            @Override
           public void run()
            {
                while(!(frame.isVisible()))
                {
                    try {
                        System.out.println("not visible");
                        sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MailSetupPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                System.out.println("after loop");
                m1.toStop=false;
            }
        }

         managewindow mngw =new managewindow();
         mngw.start();
        //m1.toStop=false;
}//GEN-LAST:event_b_okActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MailSetupPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_ok;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_user_name;
    // End of variables declaration//GEN-END:variables

}
