
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.io.IOException;
import java.net.ConnectException;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkEvent.EventType;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MailViewPanel.java
 *
 * Created on Feb 28, 2011, 12:23:26 PM
 */

/**
 *
 * @author Md. Salahuddin
 */
public class MailViewPanel extends javax.swing.JPanel {

    /** Creates new form MailViewPanel */
    public MailViewPanel() {
        initComponents();
        add(new javax.swing.JButton("hudai"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_from = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_to = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mail Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 2, 2));

        jLabel1.setText("From");
        jPanel1.add(jLabel1);
        jPanel1.add(tf_from);

        jLabel2.setText("To");
        jPanel1.add(jLabel2);
        jPanel1.add(tf_to);

        jLabel3.setText("Subject");
        jPanel1.add(jLabel3);
        jPanel1.add(tf_subject);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Content", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPane1HyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jEditorPane1HyperlinkUpdate(javax.swing.event.HyperlinkEvent evt)//GEN-FIRST:event_jEditorPane1HyperlinkUpdate
    {//GEN-HEADEREND:event_jEditorPane1HyperlinkUpdate
        // TODO add your handling code here:
        if(evt.getEventType()==HyperlinkEvent.EventType.ACTIVATED)
        {
            JFrame frame = new JFrame("");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setLayout(new BorderLayout());
            frame.add(new BrowserPanel(evt.getURL()), BorderLayout.CENTER);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_jEditorPane1HyperlinkUpdate

    public JEditorPane getEditorPane()
    {
        return jEditorPane1;
    }

    public void readMail(String user_name,String password) throws IOException
    {
          
            System.out.println("mp called");

        MailHandler mHandler = new MailHandler();
        mHandler.setProtocol("imap");
        mHandler.setURL("imap.gmail.com");
        mHandler.setUserPassword(user_name,password);
        mHandler.connect();
        mHandler.openFolder("INBOX");
        try
        {
            int cnt = mHandler.getMessageCount();
            int nCnt = mHandler.getNewMessageCount();
            System.out.println(cnt + " "+nCnt);
            System.out.println("printing in mail v panel");
            System.out.println("stoped");
            try {
                mHandler.parseMessages(this, false);
            } catch (Exception ex) {
                Logger.getLogger(MailViewPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            mHandler.closeFolder();
            tf_from.setText(mHandler.from);
            tf_to.setText(mHandler.to);
            tf_subject.setText(mHandler.subject);
        }
        catch(MessagingException ex)
        {
            Logger.getLogger(MailViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
          
         
              }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tf_from;
    private javax.swing.JTextField tf_subject;
    private javax.swing.JTextField tf_to;
    // End of variables declaration//GEN-END:variables

}
