
import java.awt.BorderLayout;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.event.HyperlinkEvent;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MailViewPanel.java
 *
 * Created on Feb 28, 2011, 12:23:26 PM
 */

/**
 *
 * @author Md. Salahuddin
 */
public class MailViewPanel extends javax.swing.JFrame {

    /** Creates new form MailViewPanel */
    public MailViewPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_from = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_to = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        closeButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mail Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 2, 2));

        jLabel1.setText("From");
        jPanel1.add(jLabel1);
        jPanel1.add(tf_from);

        jLabel2.setText("To");
        jPanel1.add(jLabel2);
        jPanel1.add(tf_to);

        jLabel3.setText("Subject");
        jPanel1.add(jLabel3);
        jPanel1.add(tf_subject);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Content", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPane1HyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane1);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jEditorPane1HyperlinkUpdate(javax.swing.event.HyperlinkEvent evt)//GEN-FIRST:event_jEditorPane1HyperlinkUpdate
    {//GEN-HEADEREND:event_jEditorPane1HyperlinkUpdate
        // TODO add your handling code here:
        if(evt.getEventType()==HyperlinkEvent.EventType.ACTIVATED)
        {
            JFrame frame = new JFrame("");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setLayout(new BorderLayout());
            frame.add(new BrowserPanel(evt.getURL()), BorderLayout.CENTER);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_jEditorPane1HyperlinkUpdate

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    public JEditorPane getEditorPane()
    {
        return jEditorPane1;
    }
    public void setTextFieldFrom(String s)
    {
        tf_from.setText(s);
    }
    public void setTextFieldTO(String s)
    {
        tf_to.setText(s);
    }
    public void setTextFieldSubject(String s)
    {
        tf_subject.setText(s);
    }

/*    public void readMail(String user_name,String password) throws IOException
    {
          
            System.out.println("mp called");

        MailHandler mHandler = new MailHandler();
        mHandler.setProtocol("imap");
        mHandler.setURL("imap.gmail.com");
        mHandler.setUserPassword(user_name,password);
        mHandler.connect();
        mHandler.openFolder("INBOX");*/
    /*    try
        {
            int cnt = mHandler.getMessageCount();
            int nCnt = mHandler.getNewMessageCount();
            System.out.println(cnt + " "+nCnt);
            System.out.println("printing in mail v panel");
            System.out.println("stoped");
            try {
                mHandler.parseMessages(false);
            } catch (Exception ex) {
                Logger.getLogger(MailViewPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("complete printing");
            mHandler.closeFolder();
            tf_from.setText(mHandler.from.getItem(0));
            tf_to.setText(mHandler.to.getItem(0));
            tf_subject.setText(mHandler.subject.getItem(0));
        }
        catch(MessagingException ex)
        {
            Logger.getLogger(MailViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
          */
         
              


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tf_from;
    private javax.swing.JTextField tf_subject;
    private javax.swing.JTextField tf_to;
    // End of variables declaration//GEN-END:variables

}
