/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.Store;
import javax.swing.table.TableColumn;
/*
 * MailList.java
 *
 * Created on Mar 12, 2011, 2:39:15 AM
 */

/**
 *
 * @author 3PSN
 */
public class MailList extends javax.swing.JPanel {

    /** Creates new form MailList */
    private  int totalmsg=10,newmsg;
    MailHandler smHandler;
    public MailList() {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_mailList = new javax.swing.JTable();
        tf_inbox = new javax.swing.JTextField();
        openMailButton = new javax.swing.JButton();

        jt_mailList.setModel(new javax.swing.table.DefaultTableModel(
            new String [] {
                "From", "Subject"
            },totalmsg
        ));
        jScrollPane1.setViewportView(jt_mailList);

        tf_inbox.setText("Inbox()");

        openMailButton.setText("Open Mail");
        openMailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_inbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(openMailButton)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_inbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(openMailButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openMailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMailButtonActionPerformed
        // TODO add your handling code here:

        int index;
        index=jt_mailList.getSelectedRow();
        System.out.println(index);
        MailViewPanel mp=new MailViewPanel();
        smHandler.getDetailMsg(index, mp);

      /*  JButton closeButton=new JButton("Close");
        closeButton.addActionListener(new ActionListener(){
        public void actionPerformed(ActionEvent e)
            {
            frame.dispose();
        }

        }); */
        mp.setTextFieldFrom(smHandler.from.getItem(index));
        mp.setTextFieldSubject(smHandler.subject.getItem(index));
        mp.setTextFieldTO(smHandler.to.getItem(index));
}//GEN-LAST:event_openMailButtonActionPerformed


    public void showMailList(Store store)
    {
       // totalmsg=10;
        smHandler = new MailHandler(store);
        smHandler.openFolder("INBOX");
        try
        {
            totalmsg = smHandler.getMessageCount();
            newmsg = smHandler.getNewMessageCount();
            initComponents();
            TableColumn tableColumnSettings0=jt_mailList.getTableHeader().getColumnModel().getColumn(0);

           // int width;
           // width=tableColumnSettings0.getWidth();

            tableColumnSettings0.setMaxWidth(200);
            tableColumnSettings0.setMinWidth(180);

           // width=tableColumnSettings0.getWidth();
           // System.out.println(width);
          //  TableColumn tableColumnSettings1=jt_mailList.getTableHeader().getColumnModel().getColumn(1);
          //  width=tableColumnSettings1.getWidth();
          //  System.out.println(width);
            System.out.println(totalmsg + " "+newmsg);
            tf_inbox.setText("Inbox("+totalmsg+"/"+newmsg+")");
            try {
                smHandler.parseMessages(false);
            } catch (IOException ex) {
                Logger.getLogger(MailList1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(MailList1.class.getName()).log(Level.SEVERE, null, ex);
            }

            System.out.println("going to print from and subject in maillist");
            for(int i=0;i<totalmsg;i++)
            {
                jt_mailList.setValueAt(smHandler.from.getItem(i),i, 0);
                jt_mailList.setValueAt(smHandler.subject.getItem(i),i, 1);
            System.out.println("Massage "+(i+1)+" #: "+smHandler.from.getItem(i)+"  :: "+smHandler.subject.getItem(i));
            }
               System.out.println("complete printing");

           // smHandler.closeFolder();

        }
        catch(MessagingException ex)
        {
           // Logger.getLogger(MailViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_mailList;
    private javax.swing.JButton openMailButton;
    private javax.swing.JTextField tf_inbox;
    // End of variables declaration//GEN-END:variables

}
